name: panda_sync
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mockito: ^5.4.4
  test: any
