name: panda_sync
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.6 # Dependency injection
  dio: ^5.4.0 # For network calls
  hive: ^2.2.3 # For local storage
  hive_flutter: ^1.1.0 # Flutter extension for Hive
  connectivity_plus: ^5.0.2 # For monitoring connectivity
  flutter_bloc: ^8.1.3 # Optional: if using Bloc for state management

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3 # For creating mocks in tests
  integration_test:
    sdk: flutter
  hive_generator: ^2.0.1 # For Hive type adapters
  build_runner: ^2.4.7 # For generating code (Hive adapters, etc.)